databases:
  - name: loki-db
    databaseName: loki
    user: loki_user

services:
  - type: web
    name: loki-backend
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn loki_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loki-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: loki-backend.onrender.com,localhost,127.0.0.1
      - key: CLIENT_URL
        value: https://loki-frontend.vercel.app # Update with your actual frontend URL
      - key: JWT_ACCESS_TOKEN_LIFETIME
        value: 604800
      - key: JWT_REFRESH_TOKEN_LIFETIME
        value: 2592000
